### ISSUE TITLE
subway screen 뷰모델 만들기

### ISSUE THREAD

**Issue by eqqmayo** [sesac-flutter/real-time-subway-arrival#24]

**Comment by S-YUN** [comment]
textfield의 onSubmitted는 사용자가 키보드에서 엔터(또는 완료) 버튼을 눌렀을 때 호출됩니다. 이는 과제에서의 '입력할때마다 검색 요청' 조건에 완전히 부합하지는 않는 것 같습니다..! 머지 후에 발견해서 이슈 재오픈 후 코멘트 달아용:) 일단 뷰모델 생성을 완료했고 문제 없이 빌드되기 때문에 이후 수정은 다른 이슈를 파서 제가 수정하도록 할게요! 수고하셨습니다👍

**Comment by eqqmayo** [comment]
확인했습니다! 꼼꼼한 리뷰 감사드립니다 👍
